### ISSUE TITLE
Several item names displayed incorrectly

### ISSUE THREAD

**Issue by Lzw104522773** [CrevsDaak/thalan#16]
I choose English for all DlcMerge and also choose English for installing this mod, but there are a few item names that are not displayed correctly. Taking "Throwing Dagger+1" as an example, see the following figure:

![QQ20240608091502](https://github.com/CrevsDaak/thalan/assets/149546927/d11905d8-12bf-4ab4-bf36-2e4561792a4c)

![QQ20240608091236](https://github.com/CrevsDaak/thalan/assets/149546927/37529f6c-c826-4243-bba7-22ab86f82e3d)

![20240608091031](https://github.com/CrevsDaak/thalan/assets/149546927/197b0aaf-87c8-486b-ac02-20910766c884)

In the Chinese language environment, there are also such issues.

**Comment by Lzw104522773** [comment]
I have solved this problem by adding the names of the problematic items in dialog.tlk, and then modifying the item names in the ITM file.

**Comment by CrevsDaak** [comment]
Thank you for the report, seems like loading the .tra with charset_wrapper was causing this issue, given the overlapping references in the .tra files (I don't have the time to fix those, not that it should ever be necessary if they are handled properly). I've made it so they are loaded only upon usage so it should be fixed now.

**Comment by Lzw104522773** [comment]
I installed v4.5.1 and checked those items, and the problem was indeed resolved. Thank you.
