### ISSUE TITLE
It does not work with a module of Tweak Antology

### ISSUE THREAD

**Issue by Krabator** [CrevsDaak/thalan#6]
Precisely : 
In the Tweak Anthology mod : https://www.gibberlings3.net/subpages/tweaks/rules/
When you select the rule modification : P&P for the "Wear Multiple Protection Items" module, the ring are altered... therefore it seems that they are not recognized by Thalandyr when I want to create the recipe : 2 ring +1 for 1 ring +2
(i have diamond and pearl and enought gold...) 

not sure it's a bug but it seems to be not compatible with this

**Comment by CrevsDaak** [comment]
Fixed by commit 3fcf5aa, thanks for the report.
